sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"
  
cache:
  pip: true
  directories:
    - $HOME/.ccache

matrix:
  include:
    - env: USE_SHARED_BROTLI=1
      sudo: true

env:
  global:
      - PATH="/usr/lib/ccache:$PATH"    

install:
  - "if [[ $USE_SHARED_BROTLI == 1 ]]; then mkdir build; cd build; cmake ../libbrotli -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib; make; sudo make install; cd ..; fi"
  - "pip install -U pip 'setuptools!=26.*'"
  - "pip install ."
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
before_script: "flake8 --max-complexity 10 src/brotli test"
script:
  - >
      if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
        py.test test/
      else
        py.test --cov brotli test/
      fi
